apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::454524533145:user/github-cicd
      username: github-cicd
      groups:
        - system:masters
