apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::454524533145:role/github-cicd
      username: github-cicd
      groups:
        - system:bootstrappers
        - system:nodes
